#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenFood.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GREENFOOD")]
	public partial class dbGreenFoodDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBINHLUAN(BINHLUAN instance);
    partial void UpdateBINHLUAN(BINHLUAN instance);
    partial void DeleteBINHLUAN(BINHLUAN instance);
    partial void InsertCHITIETDONHANG(CHITIETDONHANG instance);
    partial void UpdateCHITIETDONHANG(CHITIETDONHANG instance);
    partial void DeleteCHITIETDONHANG(CHITIETDONHANG instance);
    partial void InsertCHITIETKHUYENMAI(CHITIETKHUYENMAI instance);
    partial void UpdateCHITIETKHUYENMAI(CHITIETKHUYENMAI instance);
    partial void DeleteCHITIETKHUYENMAI(CHITIETKHUYENMAI instance);
    partial void InsertCHITIETTHUCPHAM(CHITIETTHUCPHAM instance);
    partial void UpdateCHITIETTHUCPHAM(CHITIETTHUCPHAM instance);
    partial void DeleteCHITIETTHUCPHAM(CHITIETTHUCPHAM instance);
    partial void InsertCHUONGTRINHKHUYENMAI(CHUONGTRINHKHUYENMAI instance);
    partial void UpdateCHUONGTRINHKHUYENMAI(CHUONGTRINHKHUYENMAI instance);
    partial void DeleteCHUONGTRINHKHUYENMAI(CHUONGTRINHKHUYENMAI instance);
    partial void InsertDATA_PAYMENT(DATA_PAYMENT instance);
    partial void UpdateDATA_PAYMENT(DATA_PAYMENT instance);
    partial void DeleteDATA_PAYMENT(DATA_PAYMENT instance);
    partial void InsertKHACHHANG(KHACHHANG instance);
    partial void UpdateKHACHHANG(KHACHHANG instance);
    partial void DeleteKHACHHANG(KHACHHANG instance);
    partial void InsertLOAITHUCPHAM(LOAITHUCPHAM instance);
    partial void UpdateLOAITHUCPHAM(LOAITHUCPHAM instance);
    partial void DeleteLOAITHUCPHAM(LOAITHUCPHAM instance);
    partial void InsertNHANVIEN(NHANVIEN instance);
    partial void UpdateNHANVIEN(NHANVIEN instance);
    partial void DeleteNHANVIEN(NHANVIEN instance);
    partial void InsertQUANLYDONHANG(QUANLYDONHANG instance);
    partial void UpdateQUANLYDONHANG(QUANLYDONHANG instance);
    partial void DeleteQUANLYDONHANG(QUANLYDONHANG instance);
    partial void InsertPHANQUYEN(PHANQUYEN instance);
    partial void UpdatePHANQUYEN(PHANQUYEN instance);
    partial void DeletePHANQUYEN(PHANQUYEN instance);
    partial void InsertTHANHVIEN(THANHVIEN instance);
    partial void UpdateTHANHVIEN(THANHVIEN instance);
    partial void DeleteTHANHVIEN(THANHVIEN instance);
    partial void InsertTHUCPHAM(THUCPHAM instance);
    partial void UpdateTHUCPHAM(THUCPHAM instance);
    partial void DeleteTHUCPHAM(THUCPHAM instance);
    partial void InsertTINNHANLIENHE(TINNHANLIENHE instance);
    partial void UpdateTINNHANLIENHE(TINNHANLIENHE instance);
    partial void DeleteTINNHANLIENHE(TINNHANLIENHE instance);
    #endregion
		
		public dbGreenFoodDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["GREENFOODConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbGreenFoodDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbGreenFoodDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbGreenFoodDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbGreenFoodDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BINHLUAN> BINHLUANs
		{
			get
			{
				return this.GetTable<BINHLUAN>();
			}
		}
		
		public System.Data.Linq.Table<CHITIETDONHANG> CHITIETDONHANGs
		{
			get
			{
				return this.GetTable<CHITIETDONHANG>();
			}
		}
		
		public System.Data.Linq.Table<CHITIETKHUYENMAI> CHITIETKHUYENMAIs
		{
			get
			{
				return this.GetTable<CHITIETKHUYENMAI>();
			}
		}
		
		public System.Data.Linq.Table<CHITIETTHUCPHAM> CHITIETTHUCPHAMs
		{
			get
			{
				return this.GetTable<CHITIETTHUCPHAM>();
			}
		}
		
		public System.Data.Linq.Table<CHUONGTRINHKHUYENMAI> CHUONGTRINHKHUYENMAIs
		{
			get
			{
				return this.GetTable<CHUONGTRINHKHUYENMAI>();
			}
		}
		
		public System.Data.Linq.Table<DATA_PAYMENT> DATA_PAYMENTs
		{
			get
			{
				return this.GetTable<DATA_PAYMENT>();
			}
		}
		
		public System.Data.Linq.Table<KHACHHANG> KHACHHANGs
		{
			get
			{
				return this.GetTable<KHACHHANG>();
			}
		}
		
		public System.Data.Linq.Table<LOAITHUCPHAM> LOAITHUCPHAMs
		{
			get
			{
				return this.GetTable<LOAITHUCPHAM>();
			}
		}
		
		public System.Data.Linq.Table<NHANVIEN> NHANVIENs
		{
			get
			{
				return this.GetTable<NHANVIEN>();
			}
		}
		
		public System.Data.Linq.Table<QUANLYDONHANG> QUANLYDONHANGs
		{
			get
			{
				return this.GetTable<QUANLYDONHANG>();
			}
		}
		
		public System.Data.Linq.Table<PHANQUYEN> PHANQUYENs
		{
			get
			{
				return this.GetTable<PHANQUYEN>();
			}
		}
		
		public System.Data.Linq.Table<THANHVIEN> THANHVIENs
		{
			get
			{
				return this.GetTable<THANHVIEN>();
			}
		}
		
		public System.Data.Linq.Table<THUCPHAM> THUCPHAMs
		{
			get
			{
				return this.GetTable<THUCPHAM>();
			}
		}
		
		public System.Data.Linq.Table<TINNHANLIENHE> TINNHANLIENHEs
		{
			get
			{
				return this.GetTable<TINNHANLIENHE>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BINHLUAN")]
	public partial class BINHLUAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaBL;
		
		private string _TenNguoiBL;
		
		private string _NoiDungBL;
		
		private System.Nullable<int> _MaThucPham;
		
		private System.Nullable<System.DateTime> _NgayBL;
		
		private string _Email;
		
		private System.Nullable<int> _DanhGia;
		
		private System.Nullable<int> _Duyet;
		
		private EntityRef<THUCPHAM> _THUCPHAM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBLChanging(int value);
    partial void OnMaBLChanged();
    partial void OnTenNguoiBLChanging(string value);
    partial void OnTenNguoiBLChanged();
    partial void OnNoiDungBLChanging(string value);
    partial void OnNoiDungBLChanged();
    partial void OnMaThucPhamChanging(System.Nullable<int> value);
    partial void OnMaThucPhamChanged();
    partial void OnNgayBLChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayBLChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDanhGiaChanging(System.Nullable<int> value);
    partial void OnDanhGiaChanged();
    partial void OnDuyetChanging(System.Nullable<int> value);
    partial void OnDuyetChanged();
    #endregion
		
		public BINHLUAN()
		{
			this._THUCPHAM = default(EntityRef<THUCPHAM>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBL", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaBL
		{
			get
			{
				return this._MaBL;
			}
			set
			{
				if ((this._MaBL != value))
				{
					this.OnMaBLChanging(value);
					this.SendPropertyChanging();
					this._MaBL = value;
					this.SendPropertyChanged("MaBL");
					this.OnMaBLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNguoiBL", DbType="NVarChar(50)")]
		public string TenNguoiBL
		{
			get
			{
				return this._TenNguoiBL;
			}
			set
			{
				if ((this._TenNguoiBL != value))
				{
					this.OnTenNguoiBLChanging(value);
					this.SendPropertyChanging();
					this._TenNguoiBL = value;
					this.SendPropertyChanged("TenNguoiBL");
					this.OnTenNguoiBLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDungBL", DbType="NVarChar(1000)")]
		public string NoiDungBL
		{
			get
			{
				return this._NoiDungBL;
			}
			set
			{
				if ((this._NoiDungBL != value))
				{
					this.OnNoiDungBLChanging(value);
					this.SendPropertyChanging();
					this._NoiDungBL = value;
					this.SendPropertyChanged("NoiDungBL");
					this.OnNoiDungBLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaThucPham", DbType="Int")]
		public System.Nullable<int> MaThucPham
		{
			get
			{
				return this._MaThucPham;
			}
			set
			{
				if ((this._MaThucPham != value))
				{
					if (this._THUCPHAM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaThucPhamChanging(value);
					this.SendPropertyChanging();
					this._MaThucPham = value;
					this.SendPropertyChanged("MaThucPham");
					this.OnMaThucPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBL", DbType="Date")]
		public System.Nullable<System.DateTime> NgayBL
		{
			get
			{
				return this._NgayBL;
			}
			set
			{
				if ((this._NgayBL != value))
				{
					this.OnNgayBLChanging(value);
					this.SendPropertyChanging();
					this._NgayBL = value;
					this.SendPropertyChanged("NgayBL");
					this.OnNgayBLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(200)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DanhGia", DbType="Int")]
		public System.Nullable<int> DanhGia
		{
			get
			{
				return this._DanhGia;
			}
			set
			{
				if ((this._DanhGia != value))
				{
					this.OnDanhGiaChanging(value);
					this.SendPropertyChanging();
					this._DanhGia = value;
					this.SendPropertyChanged("DanhGia");
					this.OnDanhGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Duyet", DbType="Int")]
		public System.Nullable<int> Duyet
		{
			get
			{
				return this._Duyet;
			}
			set
			{
				if ((this._Duyet != value))
				{
					this.OnDuyetChanging(value);
					this.SendPropertyChanging();
					this._Duyet = value;
					this.SendPropertyChanged("Duyet");
					this.OnDuyetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THUCPHAM_BINHLUAN", Storage="_THUCPHAM", ThisKey="MaThucPham", OtherKey="MaThucPham", IsForeignKey=true)]
		public THUCPHAM THUCPHAM
		{
			get
			{
				return this._THUCPHAM.Entity;
			}
			set
			{
				THUCPHAM previousValue = this._THUCPHAM.Entity;
				if (((previousValue != value) 
							|| (this._THUCPHAM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THUCPHAM.Entity = null;
						previousValue.BINHLUANs.Remove(this);
					}
					this._THUCPHAM.Entity = value;
					if ((value != null))
					{
						value.BINHLUANs.Add(this);
						this._MaThucPham = value.MaThucPham;
					}
					else
					{
						this._MaThucPham = default(Nullable<int>);
					}
					this.SendPropertyChanged("THUCPHAM");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHITIETDONHANG")]
	public partial class CHITIETDONHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDonHang;
		
		private int _MaThucPham;
		
		private int _MaLoaiThucPham;
		
		private System.Nullable<int> _TrongLuong;
		
		private System.Nullable<decimal> _TongTien;
		
		private System.Nullable<System.DateTime> _NgayThanhToan;
		
		private int _ThanhToan;
		
		private EntityRef<LOAITHUCPHAM> _LOAITHUCPHAM;
		
		private EntityRef<QUANLYDONHANG> _QUANLYDONHANG;
		
		private EntityRef<THUCPHAM> _THUCPHAM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDonHangChanging(int value);
    partial void OnMaDonHangChanged();
    partial void OnMaThucPhamChanging(int value);
    partial void OnMaThucPhamChanged();
    partial void OnMaLoaiThucPhamChanging(int value);
    partial void OnMaLoaiThucPhamChanged();
    partial void OnTrongLuongChanging(System.Nullable<int> value);
    partial void OnTrongLuongChanged();
    partial void OnTongTienChanging(System.Nullable<decimal> value);
    partial void OnTongTienChanged();
    partial void OnNgayThanhToanChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayThanhToanChanged();
    partial void OnThanhToanChanging(int value);
    partial void OnThanhToanChanged();
    #endregion
		
		public CHITIETDONHANG()
		{
			this._LOAITHUCPHAM = default(EntityRef<LOAITHUCPHAM>);
			this._QUANLYDONHANG = default(EntityRef<QUANLYDONHANG>);
			this._THUCPHAM = default(EntityRef<THUCPHAM>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDonHang", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaDonHang
		{
			get
			{
				return this._MaDonHang;
			}
			set
			{
				if ((this._MaDonHang != value))
				{
					if (this._QUANLYDONHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDonHangChanging(value);
					this.SendPropertyChanging();
					this._MaDonHang = value;
					this.SendPropertyChanged("MaDonHang");
					this.OnMaDonHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaThucPham", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaThucPham
		{
			get
			{
				return this._MaThucPham;
			}
			set
			{
				if ((this._MaThucPham != value))
				{
					if (this._THUCPHAM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaThucPhamChanging(value);
					this.SendPropertyChanging();
					this._MaThucPham = value;
					this.SendPropertyChanged("MaThucPham");
					this.OnMaThucPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiThucPham", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaLoaiThucPham
		{
			get
			{
				return this._MaLoaiThucPham;
			}
			set
			{
				if ((this._MaLoaiThucPham != value))
				{
					if (this._LOAITHUCPHAM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiThucPhamChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiThucPham = value;
					this.SendPropertyChanged("MaLoaiThucPham");
					this.OnMaLoaiThucPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrongLuong", DbType="Int")]
		public System.Nullable<int> TrongLuong
		{
			get
			{
				return this._TrongLuong;
			}
			set
			{
				if ((this._TrongLuong != value))
				{
					this.OnTrongLuongChanging(value);
					this.SendPropertyChanging();
					this._TrongLuong = value;
					this.SendPropertyChanged("TrongLuong");
					this.OnTrongLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTien", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> TongTien
		{
			get
			{
				return this._TongTien;
			}
			set
			{
				if ((this._TongTien != value))
				{
					this.OnTongTienChanging(value);
					this.SendPropertyChanging();
					this._TongTien = value;
					this.SendPropertyChanged("TongTien");
					this.OnTongTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayThanhToan", DbType="Date")]
		public System.Nullable<System.DateTime> NgayThanhToan
		{
			get
			{
				return this._NgayThanhToan;
			}
			set
			{
				if ((this._NgayThanhToan != value))
				{
					this.OnNgayThanhToanChanging(value);
					this.SendPropertyChanging();
					this._NgayThanhToan = value;
					this.SendPropertyChanged("NgayThanhToan");
					this.OnNgayThanhToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhToan", DbType="Int NOT NULL")]
		public int ThanhToan
		{
			get
			{
				return this._ThanhToan;
			}
			set
			{
				if ((this._ThanhToan != value))
				{
					this.OnThanhToanChanging(value);
					this.SendPropertyChanging();
					this._ThanhToan = value;
					this.SendPropertyChanged("ThanhToan");
					this.OnThanhToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAITHUCPHAM_CHITIETDONHANG", Storage="_LOAITHUCPHAM", ThisKey="MaLoaiThucPham", OtherKey="MaLoaiThucPham", IsForeignKey=true)]
		public LOAITHUCPHAM LOAITHUCPHAM
		{
			get
			{
				return this._LOAITHUCPHAM.Entity;
			}
			set
			{
				LOAITHUCPHAM previousValue = this._LOAITHUCPHAM.Entity;
				if (((previousValue != value) 
							|| (this._LOAITHUCPHAM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAITHUCPHAM.Entity = null;
						previousValue.CHITIETDONHANGs.Remove(this);
					}
					this._LOAITHUCPHAM.Entity = value;
					if ((value != null))
					{
						value.CHITIETDONHANGs.Add(this);
						this._MaLoaiThucPham = value.MaLoaiThucPham;
					}
					else
					{
						this._MaLoaiThucPham = default(int);
					}
					this.SendPropertyChanged("LOAITHUCPHAM");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QUANLYDONHANG_CHITIETDONHANG", Storage="_QUANLYDONHANG", ThisKey="MaDonHang", OtherKey="MaDonHang", IsForeignKey=true)]
		public QUANLYDONHANG QUANLYDONHANG
		{
			get
			{
				return this._QUANLYDONHANG.Entity;
			}
			set
			{
				QUANLYDONHANG previousValue = this._QUANLYDONHANG.Entity;
				if (((previousValue != value) 
							|| (this._QUANLYDONHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QUANLYDONHANG.Entity = null;
						previousValue.CHITIETDONHANGs.Remove(this);
					}
					this._QUANLYDONHANG.Entity = value;
					if ((value != null))
					{
						value.CHITIETDONHANGs.Add(this);
						this._MaDonHang = value.MaDonHang;
					}
					else
					{
						this._MaDonHang = default(int);
					}
					this.SendPropertyChanged("QUANLYDONHANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THUCPHAM_CHITIETDONHANG", Storage="_THUCPHAM", ThisKey="MaThucPham", OtherKey="MaThucPham", IsForeignKey=true)]
		public THUCPHAM THUCPHAM
		{
			get
			{
				return this._THUCPHAM.Entity;
			}
			set
			{
				THUCPHAM previousValue = this._THUCPHAM.Entity;
				if (((previousValue != value) 
							|| (this._THUCPHAM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THUCPHAM.Entity = null;
						previousValue.CHITIETDONHANGs.Remove(this);
					}
					this._THUCPHAM.Entity = value;
					if ((value != null))
					{
						value.CHITIETDONHANGs.Add(this);
						this._MaThucPham = value.MaThucPham;
					}
					else
					{
						this._MaThucPham = default(int);
					}
					this.SendPropertyChanged("THUCPHAM");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHITIETKHUYENMAI")]
	public partial class CHITIETKHUYENMAI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaCT;
		
		private System.Nullable<int> _MaKM;
		
		private System.Nullable<int> _MaThucPham;
		
		private string _TenThucPham;
		
		private System.Nullable<decimal> _Gia;
		
		private string _AnhBia;
		
		private System.Nullable<int> _GiamGia;
		
		private System.Nullable<int> _Up;
		
		private EntityRef<CHUONGTRINHKHUYENMAI> _CHUONGTRINHKHUYENMAI;
		
		private EntityRef<THUCPHAM> _THUCPHAM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCTChanging(int value);
    partial void OnMaCTChanged();
    partial void OnMaKMChanging(System.Nullable<int> value);
    partial void OnMaKMChanged();
    partial void OnMaThucPhamChanging(System.Nullable<int> value);
    partial void OnMaThucPhamChanged();
    partial void OnTenThucPhamChanging(string value);
    partial void OnTenThucPhamChanged();
    partial void OnGiaChanging(System.Nullable<decimal> value);
    partial void OnGiaChanged();
    partial void OnAnhBiaChanging(string value);
    partial void OnAnhBiaChanged();
    partial void OnGiamGiaChanging(System.Nullable<int> value);
    partial void OnGiamGiaChanged();
    partial void OnUpChanging(System.Nullable<int> value);
    partial void OnUpChanged();
    #endregion
		
		public CHITIETKHUYENMAI()
		{
			this._CHUONGTRINHKHUYENMAI = default(EntityRef<CHUONGTRINHKHUYENMAI>);
			this._THUCPHAM = default(EntityRef<THUCPHAM>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaCT
		{
			get
			{
				return this._MaCT;
			}
			set
			{
				if ((this._MaCT != value))
				{
					this.OnMaCTChanging(value);
					this.SendPropertyChanging();
					this._MaCT = value;
					this.SendPropertyChanged("MaCT");
					this.OnMaCTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKM", DbType="Int")]
		public System.Nullable<int> MaKM
		{
			get
			{
				return this._MaKM;
			}
			set
			{
				if ((this._MaKM != value))
				{
					if (this._CHUONGTRINHKHUYENMAI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKMChanging(value);
					this.SendPropertyChanging();
					this._MaKM = value;
					this.SendPropertyChanged("MaKM");
					this.OnMaKMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaThucPham", DbType="Int")]
		public System.Nullable<int> MaThucPham
		{
			get
			{
				return this._MaThucPham;
			}
			set
			{
				if ((this._MaThucPham != value))
				{
					if (this._THUCPHAM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaThucPhamChanging(value);
					this.SendPropertyChanging();
					this._MaThucPham = value;
					this.SendPropertyChanged("MaThucPham");
					this.OnMaThucPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenThucPham", DbType="NVarChar(30)")]
		public string TenThucPham
		{
			get
			{
				return this._TenThucPham;
			}
			set
			{
				if ((this._TenThucPham != value))
				{
					this.OnTenThucPhamChanging(value);
					this.SendPropertyChanging();
					this._TenThucPham = value;
					this.SendPropertyChanged("TenThucPham");
					this.OnTenThucPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Money")]
		public System.Nullable<decimal> Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnhBia", DbType="NVarChar(500)")]
		public string AnhBia
		{
			get
			{
				return this._AnhBia;
			}
			set
			{
				if ((this._AnhBia != value))
				{
					this.OnAnhBiaChanging(value);
					this.SendPropertyChanging();
					this._AnhBia = value;
					this.SendPropertyChanged("AnhBia");
					this.OnAnhBiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiamGia", DbType="Int")]
		public System.Nullable<int> GiamGia
		{
			get
			{
				return this._GiamGia;
			}
			set
			{
				if ((this._GiamGia != value))
				{
					this.OnGiamGiaChanging(value);
					this.SendPropertyChanging();
					this._GiamGia = value;
					this.SendPropertyChanged("GiamGia");
					this.OnGiamGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Up", DbType="Int")]
		public System.Nullable<int> Up
		{
			get
			{
				return this._Up;
			}
			set
			{
				if ((this._Up != value))
				{
					this.OnUpChanging(value);
					this.SendPropertyChanging();
					this._Up = value;
					this.SendPropertyChanged("Up");
					this.OnUpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHUONGTRINHKHUYENMAI_CHITIETKHUYENMAI", Storage="_CHUONGTRINHKHUYENMAI", ThisKey="MaKM", OtherKey="MaKM", IsForeignKey=true)]
		public CHUONGTRINHKHUYENMAI CHUONGTRINHKHUYENMAI
		{
			get
			{
				return this._CHUONGTRINHKHUYENMAI.Entity;
			}
			set
			{
				CHUONGTRINHKHUYENMAI previousValue = this._CHUONGTRINHKHUYENMAI.Entity;
				if (((previousValue != value) 
							|| (this._CHUONGTRINHKHUYENMAI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CHUONGTRINHKHUYENMAI.Entity = null;
						previousValue.CHITIETKHUYENMAIs.Remove(this);
					}
					this._CHUONGTRINHKHUYENMAI.Entity = value;
					if ((value != null))
					{
						value.CHITIETKHUYENMAIs.Add(this);
						this._MaKM = value.MaKM;
					}
					else
					{
						this._MaKM = default(Nullable<int>);
					}
					this.SendPropertyChanged("CHUONGTRINHKHUYENMAI");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THUCPHAM_CHITIETKHUYENMAI", Storage="_THUCPHAM", ThisKey="MaThucPham", OtherKey="MaThucPham", IsForeignKey=true)]
		public THUCPHAM THUCPHAM
		{
			get
			{
				return this._THUCPHAM.Entity;
			}
			set
			{
				THUCPHAM previousValue = this._THUCPHAM.Entity;
				if (((previousValue != value) 
							|| (this._THUCPHAM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THUCPHAM.Entity = null;
						previousValue.CHITIETKHUYENMAIs.Remove(this);
					}
					this._THUCPHAM.Entity = value;
					if ((value != null))
					{
						value.CHITIETKHUYENMAIs.Add(this);
						this._MaThucPham = value.MaThucPham;
					}
					else
					{
						this._MaThucPham = default(Nullable<int>);
					}
					this.SendPropertyChanged("THUCPHAM");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHITIETTHUCPHAM")]
	public partial class CHITIETTHUCPHAM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _STT;
		
		private System.Nullable<int> _MaThucPham;
		
		private System.Nullable<int> _MaLoaiThucPham;
		
		private string _TenThucPham;
		
		private System.Nullable<decimal> _Gia;
		
		private string _Mota;
		
		private int _TrongLuong;
		
		private string _AnhBia;
		
		private System.Nullable<System.DateTime> _HanSuDung;
		
		private System.Nullable<int> _SoLuongBan;
		
		private System.Nullable<int> _SoLuongDaBan;
		
		private EntityRef<LOAITHUCPHAM> _LOAITHUCPHAM;
		
		private EntityRef<THUCPHAM> _THUCPHAM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTTChanging(int value);
    partial void OnSTTChanged();
    partial void OnMaThucPhamChanging(System.Nullable<int> value);
    partial void OnMaThucPhamChanged();
    partial void OnMaLoaiThucPhamChanging(System.Nullable<int> value);
    partial void OnMaLoaiThucPhamChanged();
    partial void OnTenThucPhamChanging(string value);
    partial void OnTenThucPhamChanged();
    partial void OnGiaChanging(System.Nullable<decimal> value);
    partial void OnGiaChanged();
    partial void OnMotaChanging(string value);
    partial void OnMotaChanged();
    partial void OnTrongLuongChanging(int value);
    partial void OnTrongLuongChanged();
    partial void OnAnhBiaChanging(string value);
    partial void OnAnhBiaChanged();
    partial void OnHanSuDungChanging(System.Nullable<System.DateTime> value);
    partial void OnHanSuDungChanged();
    partial void OnSoLuongBanChanging(System.Nullable<int> value);
    partial void OnSoLuongBanChanged();
    partial void OnSoLuongDaBanChanging(System.Nullable<int> value);
    partial void OnSoLuongDaBanChanged();
    #endregion
		
		public CHITIETTHUCPHAM()
		{
			this._LOAITHUCPHAM = default(EntityRef<LOAITHUCPHAM>);
			this._THUCPHAM = default(EntityRef<THUCPHAM>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this.OnSTTChanging(value);
					this.SendPropertyChanging();
					this._STT = value;
					this.SendPropertyChanged("STT");
					this.OnSTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaThucPham", DbType="Int")]
		public System.Nullable<int> MaThucPham
		{
			get
			{
				return this._MaThucPham;
			}
			set
			{
				if ((this._MaThucPham != value))
				{
					if (this._THUCPHAM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaThucPhamChanging(value);
					this.SendPropertyChanging();
					this._MaThucPham = value;
					this.SendPropertyChanged("MaThucPham");
					this.OnMaThucPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiThucPham", DbType="Int")]
		public System.Nullable<int> MaLoaiThucPham
		{
			get
			{
				return this._MaLoaiThucPham;
			}
			set
			{
				if ((this._MaLoaiThucPham != value))
				{
					if (this._LOAITHUCPHAM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiThucPhamChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiThucPham = value;
					this.SendPropertyChanged("MaLoaiThucPham");
					this.OnMaLoaiThucPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenThucPham", DbType="NVarChar(30)")]
		public string TenThucPham
		{
			get
			{
				return this._TenThucPham;
			}
			set
			{
				if ((this._TenThucPham != value))
				{
					this.OnTenThucPhamChanging(value);
					this.SendPropertyChanging();
					this._TenThucPham = value;
					this.SendPropertyChanged("TenThucPham");
					this.OnTenThucPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Money")]
		public System.Nullable<decimal> Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mota", DbType="NVarChar(4000)")]
		public string Mota
		{
			get
			{
				return this._Mota;
			}
			set
			{
				if ((this._Mota != value))
				{
					this.OnMotaChanging(value);
					this.SendPropertyChanging();
					this._Mota = value;
					this.SendPropertyChanged("Mota");
					this.OnMotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrongLuong", DbType="Int NOT NULL")]
		public int TrongLuong
		{
			get
			{
				return this._TrongLuong;
			}
			set
			{
				if ((this._TrongLuong != value))
				{
					this.OnTrongLuongChanging(value);
					this.SendPropertyChanging();
					this._TrongLuong = value;
					this.SendPropertyChanged("TrongLuong");
					this.OnTrongLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnhBia", DbType="NVarChar(500)")]
		public string AnhBia
		{
			get
			{
				return this._AnhBia;
			}
			set
			{
				if ((this._AnhBia != value))
				{
					this.OnAnhBiaChanging(value);
					this.SendPropertyChanging();
					this._AnhBia = value;
					this.SendPropertyChanged("AnhBia");
					this.OnAnhBiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HanSuDung", DbType="Date")]
		public System.Nullable<System.DateTime> HanSuDung
		{
			get
			{
				return this._HanSuDung;
			}
			set
			{
				if ((this._HanSuDung != value))
				{
					this.OnHanSuDungChanging(value);
					this.SendPropertyChanging();
					this._HanSuDung = value;
					this.SendPropertyChanged("HanSuDung");
					this.OnHanSuDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongBan", DbType="Int")]
		public System.Nullable<int> SoLuongBan
		{
			get
			{
				return this._SoLuongBan;
			}
			set
			{
				if ((this._SoLuongBan != value))
				{
					this.OnSoLuongBanChanging(value);
					this.SendPropertyChanging();
					this._SoLuongBan = value;
					this.SendPropertyChanged("SoLuongBan");
					this.OnSoLuongBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongDaBan", DbType="Int")]
		public System.Nullable<int> SoLuongDaBan
		{
			get
			{
				return this._SoLuongDaBan;
			}
			set
			{
				if ((this._SoLuongDaBan != value))
				{
					this.OnSoLuongDaBanChanging(value);
					this.SendPropertyChanging();
					this._SoLuongDaBan = value;
					this.SendPropertyChanged("SoLuongDaBan");
					this.OnSoLuongDaBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAITHUCPHAM_CHITIETTHUCPHAM", Storage="_LOAITHUCPHAM", ThisKey="MaLoaiThucPham", OtherKey="MaLoaiThucPham", IsForeignKey=true)]
		public LOAITHUCPHAM LOAITHUCPHAM
		{
			get
			{
				return this._LOAITHUCPHAM.Entity;
			}
			set
			{
				LOAITHUCPHAM previousValue = this._LOAITHUCPHAM.Entity;
				if (((previousValue != value) 
							|| (this._LOAITHUCPHAM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAITHUCPHAM.Entity = null;
						previousValue.CHITIETTHUCPHAMs.Remove(this);
					}
					this._LOAITHUCPHAM.Entity = value;
					if ((value != null))
					{
						value.CHITIETTHUCPHAMs.Add(this);
						this._MaLoaiThucPham = value.MaLoaiThucPham;
					}
					else
					{
						this._MaLoaiThucPham = default(Nullable<int>);
					}
					this.SendPropertyChanged("LOAITHUCPHAM");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THUCPHAM_CHITIETTHUCPHAM", Storage="_THUCPHAM", ThisKey="MaThucPham", OtherKey="MaThucPham", IsForeignKey=true)]
		public THUCPHAM THUCPHAM
		{
			get
			{
				return this._THUCPHAM.Entity;
			}
			set
			{
				THUCPHAM previousValue = this._THUCPHAM.Entity;
				if (((previousValue != value) 
							|| (this._THUCPHAM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THUCPHAM.Entity = null;
						previousValue.CHITIETTHUCPHAMs.Remove(this);
					}
					this._THUCPHAM.Entity = value;
					if ((value != null))
					{
						value.CHITIETTHUCPHAMs.Add(this);
						this._MaThucPham = value.MaThucPham;
					}
					else
					{
						this._MaThucPham = default(Nullable<int>);
					}
					this.SendPropertyChanged("THUCPHAM");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHUONGTRINHKHUYENMAI")]
	public partial class CHUONGTRINHKHUYENMAI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaKM;
		
		private string _TenKM;
		
		private System.Nullable<System.DateTime> _ThoiGianBD;
		
		private System.Nullable<System.DateTime> _ThoiGianKT;
		
		private System.Nullable<int> _Up;
		
		private EntitySet<CHITIETKHUYENMAI> _CHITIETKHUYENMAIs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKMChanging(int value);
    partial void OnMaKMChanged();
    partial void OnTenKMChanging(string value);
    partial void OnTenKMChanged();
    partial void OnThoiGianBDChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianBDChanged();
    partial void OnThoiGianKTChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianKTChanged();
    partial void OnUpChanging(System.Nullable<int> value);
    partial void OnUpChanged();
    #endregion
		
		public CHUONGTRINHKHUYENMAI()
		{
			this._CHITIETKHUYENMAIs = new EntitySet<CHITIETKHUYENMAI>(new Action<CHITIETKHUYENMAI>(this.attach_CHITIETKHUYENMAIs), new Action<CHITIETKHUYENMAI>(this.detach_CHITIETKHUYENMAIs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKM", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaKM
		{
			get
			{
				return this._MaKM;
			}
			set
			{
				if ((this._MaKM != value))
				{
					this.OnMaKMChanging(value);
					this.SendPropertyChanging();
					this._MaKM = value;
					this.SendPropertyChanged("MaKM");
					this.OnMaKMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKM", DbType="NVarChar(100)")]
		public string TenKM
		{
			get
			{
				return this._TenKM;
			}
			set
			{
				if ((this._TenKM != value))
				{
					this.OnTenKMChanging(value);
					this.SendPropertyChanging();
					this._TenKM = value;
					this.SendPropertyChanged("TenKM");
					this.OnTenKMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianBD", DbType="Date")]
		public System.Nullable<System.DateTime> ThoiGianBD
		{
			get
			{
				return this._ThoiGianBD;
			}
			set
			{
				if ((this._ThoiGianBD != value))
				{
					this.OnThoiGianBDChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianBD = value;
					this.SendPropertyChanged("ThoiGianBD");
					this.OnThoiGianBDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianKT", DbType="Date")]
		public System.Nullable<System.DateTime> ThoiGianKT
		{
			get
			{
				return this._ThoiGianKT;
			}
			set
			{
				if ((this._ThoiGianKT != value))
				{
					this.OnThoiGianKTChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianKT = value;
					this.SendPropertyChanged("ThoiGianKT");
					this.OnThoiGianKTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Up", DbType="Int")]
		public System.Nullable<int> Up
		{
			get
			{
				return this._Up;
			}
			set
			{
				if ((this._Up != value))
				{
					this.OnUpChanging(value);
					this.SendPropertyChanging();
					this._Up = value;
					this.SendPropertyChanged("Up");
					this.OnUpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHUONGTRINHKHUYENMAI_CHITIETKHUYENMAI", Storage="_CHITIETKHUYENMAIs", ThisKey="MaKM", OtherKey="MaKM")]
		public EntitySet<CHITIETKHUYENMAI> CHITIETKHUYENMAIs
		{
			get
			{
				return this._CHITIETKHUYENMAIs;
			}
			set
			{
				this._CHITIETKHUYENMAIs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETKHUYENMAIs(CHITIETKHUYENMAI entity)
		{
			this.SendPropertyChanging();
			entity.CHUONGTRINHKHUYENMAI = this;
		}
		
		private void detach_CHITIETKHUYENMAIs(CHITIETKHUYENMAI entity)
		{
			this.SendPropertyChanging();
			entity.CHUONGTRINHKHUYENMAI = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DATA_PAYMENT")]
	public partial class DATA_PAYMENT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _MaDonHang;
		
		private string _paymentMethod;
		
		private string _bankCode;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnMaDonHangChanging(System.Nullable<int> value);
    partial void OnMaDonHangChanged();
    partial void OnpaymentMethodChanging(string value);
    partial void OnpaymentMethodChanged();
    partial void OnbankCodeChanging(string value);
    partial void OnbankCodeChanged();
    #endregion
		
		public DATA_PAYMENT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDonHang", DbType="Int")]
		public System.Nullable<int> MaDonHang
		{
			get
			{
				return this._MaDonHang;
			}
			set
			{
				if ((this._MaDonHang != value))
				{
					this.OnMaDonHangChanging(value);
					this.SendPropertyChanging();
					this._MaDonHang = value;
					this.SendPropertyChanged("MaDonHang");
					this.OnMaDonHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paymentMethod", DbType="VarChar(10)")]
		public string paymentMethod
		{
			get
			{
				return this._paymentMethod;
			}
			set
			{
				if ((this._paymentMethod != value))
				{
					this.OnpaymentMethodChanging(value);
					this.SendPropertyChanging();
					this._paymentMethod = value;
					this.SendPropertyChanged("paymentMethod");
					this.OnpaymentMethodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bankCode", DbType="VarChar(10)")]
		public string bankCode
		{
			get
			{
				return this._bankCode;
			}
			set
			{
				if ((this._bankCode != value))
				{
					this.OnbankCodeChanging(value);
					this.SendPropertyChanging();
					this._bankCode = value;
					this.SendPropertyChanged("bankCode");
					this.OnbankCodeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHACHHANG")]
	public partial class KHACHHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaKH;
		
		private string _HoTenKH;
		
		private string _DienThoai;
		
		private string _DiaChi;
		
		private string _Email;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKHChanging(int value);
    partial void OnMaKHChanged();
    partial void OnHoTenKHChanging(string value);
    partial void OnHoTenKHChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public KHACHHANG()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTenKH", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string HoTenKH
		{
			get
			{
				return this._HoTenKH;
			}
			set
			{
				if ((this._HoTenKH != value))
				{
					this.OnHoTenKHChanging(value);
					this.SendPropertyChanging();
					this._HoTenKH = value;
					this.SendPropertyChanged("HoTenKH");
					this.OnHoTenKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="Char(12)")]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this.OnDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._DienThoai = value;
					this.SendPropertyChanged("DienThoai");
					this.OnDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAITHUCPHAM")]
	public partial class LOAITHUCPHAM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaLoaiThucPham;
		
		private string _TenLoaiThucPham;
		
		private EntitySet<CHITIETDONHANG> _CHITIETDONHANGs;
		
		private EntitySet<CHITIETTHUCPHAM> _CHITIETTHUCPHAMs;
		
		private EntitySet<THUCPHAM> _THUCPHAMs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiThucPhamChanging(int value);
    partial void OnMaLoaiThucPhamChanged();
    partial void OnTenLoaiThucPhamChanging(string value);
    partial void OnTenLoaiThucPhamChanged();
    #endregion
		
		public LOAITHUCPHAM()
		{
			this._CHITIETDONHANGs = new EntitySet<CHITIETDONHANG>(new Action<CHITIETDONHANG>(this.attach_CHITIETDONHANGs), new Action<CHITIETDONHANG>(this.detach_CHITIETDONHANGs));
			this._CHITIETTHUCPHAMs = new EntitySet<CHITIETTHUCPHAM>(new Action<CHITIETTHUCPHAM>(this.attach_CHITIETTHUCPHAMs), new Action<CHITIETTHUCPHAM>(this.detach_CHITIETTHUCPHAMs));
			this._THUCPHAMs = new EntitySet<THUCPHAM>(new Action<THUCPHAM>(this.attach_THUCPHAMs), new Action<THUCPHAM>(this.detach_THUCPHAMs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiThucPham", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaLoaiThucPham
		{
			get
			{
				return this._MaLoaiThucPham;
			}
			set
			{
				if ((this._MaLoaiThucPham != value))
				{
					this.OnMaLoaiThucPhamChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiThucPham = value;
					this.SendPropertyChanged("MaLoaiThucPham");
					this.OnMaLoaiThucPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoaiThucPham", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenLoaiThucPham
		{
			get
			{
				return this._TenLoaiThucPham;
			}
			set
			{
				if ((this._TenLoaiThucPham != value))
				{
					this.OnTenLoaiThucPhamChanging(value);
					this.SendPropertyChanging();
					this._TenLoaiThucPham = value;
					this.SendPropertyChanged("TenLoaiThucPham");
					this.OnTenLoaiThucPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAITHUCPHAM_CHITIETDONHANG", Storage="_CHITIETDONHANGs", ThisKey="MaLoaiThucPham", OtherKey="MaLoaiThucPham")]
		public EntitySet<CHITIETDONHANG> CHITIETDONHANGs
		{
			get
			{
				return this._CHITIETDONHANGs;
			}
			set
			{
				this._CHITIETDONHANGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAITHUCPHAM_CHITIETTHUCPHAM", Storage="_CHITIETTHUCPHAMs", ThisKey="MaLoaiThucPham", OtherKey="MaLoaiThucPham")]
		public EntitySet<CHITIETTHUCPHAM> CHITIETTHUCPHAMs
		{
			get
			{
				return this._CHITIETTHUCPHAMs;
			}
			set
			{
				this._CHITIETTHUCPHAMs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAITHUCPHAM_THUCPHAM", Storage="_THUCPHAMs", ThisKey="MaLoaiThucPham", OtherKey="MaLoaiThucPham")]
		public EntitySet<THUCPHAM> THUCPHAMs
		{
			get
			{
				return this._THUCPHAMs;
			}
			set
			{
				this._THUCPHAMs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETDONHANGs(CHITIETDONHANG entity)
		{
			this.SendPropertyChanging();
			entity.LOAITHUCPHAM = this;
		}
		
		private void detach_CHITIETDONHANGs(CHITIETDONHANG entity)
		{
			this.SendPropertyChanging();
			entity.LOAITHUCPHAM = null;
		}
		
		private void attach_CHITIETTHUCPHAMs(CHITIETTHUCPHAM entity)
		{
			this.SendPropertyChanging();
			entity.LOAITHUCPHAM = this;
		}
		
		private void detach_CHITIETTHUCPHAMs(CHITIETTHUCPHAM entity)
		{
			this.SendPropertyChanging();
			entity.LOAITHUCPHAM = null;
		}
		
		private void attach_THUCPHAMs(THUCPHAM entity)
		{
			this.SendPropertyChanging();
			entity.LOAITHUCPHAM = this;
		}
		
		private void detach_THUCPHAMs(THUCPHAM entity)
		{
			this.SendPropertyChanging();
			entity.LOAITHUCPHAM = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHANVIEN")]
	public partial class NHANVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaNV;
		
		private string _HoTenNV;
		
		private string _ChucVu;
		
		private string _DienThoai;
		
		private string _GioiTinh;
		
		private string _DiaChi;
		
		private string _Email;
		
		private string _UserName;
		
		private string _Pw;
		
		private System.Nullable<int> _MaPQ;
		
		private string _Facebook;
		
		private EntityRef<PHANQUYEN> _PHANQUYEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNVChanging(int value);
    partial void OnMaNVChanged();
    partial void OnHoTenNVChanging(string value);
    partial void OnHoTenNVChanged();
    partial void OnChucVuChanging(string value);
    partial void OnChucVuChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPwChanging(string value);
    partial void OnPwChanged();
    partial void OnMaPQChanging(System.Nullable<int> value);
    partial void OnMaPQChanged();
    partial void OnFacebookChanging(string value);
    partial void OnFacebookChanged();
    #endregion
		
		public NHANVIEN()
		{
			this._PHANQUYEN = default(EntityRef<PHANQUYEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTenNV", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string HoTenNV
		{
			get
			{
				return this._HoTenNV;
			}
			set
			{
				if ((this._HoTenNV != value))
				{
					this.OnHoTenNVChanging(value);
					this.SendPropertyChanging();
					this._HoTenNV = value;
					this.SendPropertyChanged("HoTenNV");
					this.OnHoTenNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChucVu", DbType="NVarChar(50)")]
		public string ChucVu
		{
			get
			{
				return this._ChucVu;
			}
			set
			{
				if ((this._ChucVu != value))
				{
					this.OnChucVuChanging(value);
					this.SendPropertyChanging();
					this._ChucVu = value;
					this.SendPropertyChanged("ChucVu");
					this.OnChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="Char(12)")]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this.OnDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._DienThoai = value;
					this.SendPropertyChanged("DienThoai");
					this.OnDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(6) NOT NULL", CanBeNull=false)]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pw", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Pw
		{
			get
			{
				return this._Pw;
			}
			set
			{
				if ((this._Pw != value))
				{
					this.OnPwChanging(value);
					this.SendPropertyChanging();
					this._Pw = value;
					this.SendPropertyChanged("Pw");
					this.OnPwChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPQ", DbType="Int")]
		public System.Nullable<int> MaPQ
		{
			get
			{
				return this._MaPQ;
			}
			set
			{
				if ((this._MaPQ != value))
				{
					if (this._PHANQUYEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPQChanging(value);
					this.SendPropertyChanging();
					this._MaPQ = value;
					this.SendPropertyChanged("MaPQ");
					this.OnMaPQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Facebook", DbType="VarChar(255)")]
		public string Facebook
		{
			get
			{
				return this._Facebook;
			}
			set
			{
				if ((this._Facebook != value))
				{
					this.OnFacebookChanging(value);
					this.SendPropertyChanging();
					this._Facebook = value;
					this.SendPropertyChanged("Facebook");
					this.OnFacebookChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHANQUYEN_NHANVIEN", Storage="_PHANQUYEN", ThisKey="MaPQ", OtherKey="MaPQ", IsForeignKey=true)]
		public PHANQUYEN PHANQUYEN
		{
			get
			{
				return this._PHANQUYEN.Entity;
			}
			set
			{
				PHANQUYEN previousValue = this._PHANQUYEN.Entity;
				if (((previousValue != value) 
							|| (this._PHANQUYEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHANQUYEN.Entity = null;
						previousValue.NHANVIENs.Remove(this);
					}
					this._PHANQUYEN.Entity = value;
					if ((value != null))
					{
						value.NHANVIENs.Add(this);
						this._MaPQ = value.MaPQ;
					}
					else
					{
						this._MaPQ = default(Nullable<int>);
					}
					this.SendPropertyChanged("PHANQUYEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QUANLYDONHANG")]
	public partial class QUANLYDONHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDonHang;
		
		private System.Nullable<int> _MaKH;
		
		private System.Nullable<System.DateTime> _NgayDat;
		
		private System.Nullable<System.DateTime> _NgayGiao;
		
		private string _GhiChu;
		
		private EntitySet<CHITIETDONHANG> _CHITIETDONHANGs;
		
		private EntityRef<THANHVIEN> _THANHVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDonHangChanging(int value);
    partial void OnMaDonHangChanged();
    partial void OnMaKHChanging(System.Nullable<int> value);
    partial void OnMaKHChanged();
    partial void OnNgayDatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDatChanged();
    partial void OnNgayGiaoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayGiaoChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public QUANLYDONHANG()
		{
			this._CHITIETDONHANGs = new EntitySet<CHITIETDONHANG>(new Action<CHITIETDONHANG>(this.attach_CHITIETDONHANGs), new Action<CHITIETDONHANG>(this.detach_CHITIETDONHANGs));
			this._THANHVIEN = default(EntityRef<THANHVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDonHang", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaDonHang
		{
			get
			{
				return this._MaDonHang;
			}
			set
			{
				if ((this._MaDonHang != value))
				{
					this.OnMaDonHangChanging(value);
					this.SendPropertyChanging();
					this._MaDonHang = value;
					this.SendPropertyChanged("MaDonHang");
					this.OnMaDonHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Int")]
		public System.Nullable<int> MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._THANHVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDat", DbType="Date")]
		public System.Nullable<System.DateTime> NgayDat
		{
			get
			{
				return this._NgayDat;
			}
			set
			{
				if ((this._NgayDat != value))
				{
					this.OnNgayDatChanging(value);
					this.SendPropertyChanging();
					this._NgayDat = value;
					this.SendPropertyChanged("NgayDat");
					this.OnNgayDatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayGiao", DbType="Date")]
		public System.Nullable<System.DateTime> NgayGiao
		{
			get
			{
				return this._NgayGiao;
			}
			set
			{
				if ((this._NgayGiao != value))
				{
					this.OnNgayGiaoChanging(value);
					this.SendPropertyChanging();
					this._NgayGiao = value;
					this.SendPropertyChanged("NgayGiao");
					this.OnNgayGiaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(50)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QUANLYDONHANG_CHITIETDONHANG", Storage="_CHITIETDONHANGs", ThisKey="MaDonHang", OtherKey="MaDonHang")]
		public EntitySet<CHITIETDONHANG> CHITIETDONHANGs
		{
			get
			{
				return this._CHITIETDONHANGs;
			}
			set
			{
				this._CHITIETDONHANGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THANHVIEN_QUANLYDONHANG", Storage="_THANHVIEN", ThisKey="MaKH", OtherKey="MaTV", IsForeignKey=true)]
		public THANHVIEN THANHVIEN
		{
			get
			{
				return this._THANHVIEN.Entity;
			}
			set
			{
				THANHVIEN previousValue = this._THANHVIEN.Entity;
				if (((previousValue != value) 
							|| (this._THANHVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THANHVIEN.Entity = null;
						previousValue.QUANLYDONHANGs.Remove(this);
					}
					this._THANHVIEN.Entity = value;
					if ((value != null))
					{
						value.QUANLYDONHANGs.Add(this);
						this._MaKH = value.MaTV;
					}
					else
					{
						this._MaKH = default(Nullable<int>);
					}
					this.SendPropertyChanged("THANHVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETDONHANGs(CHITIETDONHANG entity)
		{
			this.SendPropertyChanging();
			entity.QUANLYDONHANG = this;
		}
		
		private void detach_CHITIETDONHANGs(CHITIETDONHANG entity)
		{
			this.SendPropertyChanging();
			entity.QUANLYDONHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHANQUYEN")]
	public partial class PHANQUYEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaPQ;
		
		private string _TenPQ;
		
		private EntitySet<NHANVIEN> _NHANVIENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPQChanging(int value);
    partial void OnMaPQChanged();
    partial void OnTenPQChanging(string value);
    partial void OnTenPQChanged();
    #endregion
		
		public PHANQUYEN()
		{
			this._NHANVIENs = new EntitySet<NHANVIEN>(new Action<NHANVIEN>(this.attach_NHANVIENs), new Action<NHANVIEN>(this.detach_NHANVIENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPQ", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaPQ
		{
			get
			{
				return this._MaPQ;
			}
			set
			{
				if ((this._MaPQ != value))
				{
					this.OnMaPQChanging(value);
					this.SendPropertyChanging();
					this._MaPQ = value;
					this.SendPropertyChanged("MaPQ");
					this.OnMaPQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPQ", DbType="NVarChar(10)")]
		public string TenPQ
		{
			get
			{
				return this._TenPQ;
			}
			set
			{
				if ((this._TenPQ != value))
				{
					this.OnTenPQChanging(value);
					this.SendPropertyChanging();
					this._TenPQ = value;
					this.SendPropertyChanged("TenPQ");
					this.OnTenPQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHANQUYEN_NHANVIEN", Storage="_NHANVIENs", ThisKey="MaPQ", OtherKey="MaPQ")]
		public EntitySet<NHANVIEN> NHANVIENs
		{
			get
			{
				return this._NHANVIENs;
			}
			set
			{
				this._NHANVIENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NHANVIENs(NHANVIEN entity)
		{
			this.SendPropertyChanging();
			entity.PHANQUYEN = this;
		}
		
		private void detach_NHANVIENs(NHANVIEN entity)
		{
			this.SendPropertyChanging();
			entity.PHANQUYEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THANHVIEN")]
	public partial class THANHVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaTV;
		
		private string _UserName;
		
		private string _Pw;
		
		private string _HoTenTV;
		
		private string _DienThoai;
		
		private string _GioiTinh;
		
		private string _DiaChi;
		
		private string _Email;
		
		private System.Nullable<System.DateTime> _NgayDK;
		
		private EntitySet<QUANLYDONHANG> _QUANLYDONHANGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTVChanging(int value);
    partial void OnMaTVChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPwChanging(string value);
    partial void OnPwChanged();
    partial void OnHoTenTVChanging(string value);
    partial void OnHoTenTVChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnNgayDKChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDKChanged();
    #endregion
		
		public THANHVIEN()
		{
			this._QUANLYDONHANGs = new EntitySet<QUANLYDONHANG>(new Action<QUANLYDONHANG>(this.attach_QUANLYDONHANGs), new Action<QUANLYDONHANG>(this.detach_QUANLYDONHANGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaTV
		{
			get
			{
				return this._MaTV;
			}
			set
			{
				if ((this._MaTV != value))
				{
					this.OnMaTVChanging(value);
					this.SendPropertyChanging();
					this._MaTV = value;
					this.SendPropertyChanged("MaTV");
					this.OnMaTVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(50)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pw", DbType="VarChar(50)")]
		public string Pw
		{
			get
			{
				return this._Pw;
			}
			set
			{
				if ((this._Pw != value))
				{
					this.OnPwChanging(value);
					this.SendPropertyChanging();
					this._Pw = value;
					this.SendPropertyChanged("Pw");
					this.OnPwChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTenTV", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string HoTenTV
		{
			get
			{
				return this._HoTenTV;
			}
			set
			{
				if ((this._HoTenTV != value))
				{
					this.OnHoTenTVChanging(value);
					this.SendPropertyChanging();
					this._HoTenTV = value;
					this.SendPropertyChanged("HoTenTV");
					this.OnHoTenTVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="Char(12)")]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this.OnDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._DienThoai = value;
					this.SendPropertyChanged("DienThoai");
					this.OnDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(6) NOT NULL", CanBeNull=false)]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDK", DbType="Date")]
		public System.Nullable<System.DateTime> NgayDK
		{
			get
			{
				return this._NgayDK;
			}
			set
			{
				if ((this._NgayDK != value))
				{
					this.OnNgayDKChanging(value);
					this.SendPropertyChanging();
					this._NgayDK = value;
					this.SendPropertyChanged("NgayDK");
					this.OnNgayDKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THANHVIEN_QUANLYDONHANG", Storage="_QUANLYDONHANGs", ThisKey="MaTV", OtherKey="MaKH")]
		public EntitySet<QUANLYDONHANG> QUANLYDONHANGs
		{
			get
			{
				return this._QUANLYDONHANGs;
			}
			set
			{
				this._QUANLYDONHANGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_QUANLYDONHANGs(QUANLYDONHANG entity)
		{
			this.SendPropertyChanging();
			entity.THANHVIEN = this;
		}
		
		private void detach_QUANLYDONHANGs(QUANLYDONHANG entity)
		{
			this.SendPropertyChanging();
			entity.THANHVIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THUCPHAM")]
	public partial class THUCPHAM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaThucPham;
		
		private string _TenThucPham;
		
		private System.Nullable<int> _MaLoaiThucPham;
		
		private string _UserName;
		
		private System.Nullable<System.DateTime> _NgayDang;
		
		private System.Nullable<int> _Duyet;
		
		private System.Nullable<int> _CheckSale;
		
		private System.Nullable<double> _TrungBinhDanhGia;
		
		private System.Nullable<int> _GiamGia;
		
		private EntitySet<BINHLUAN> _BINHLUANs;
		
		private EntitySet<CHITIETDONHANG> _CHITIETDONHANGs;
		
		private EntitySet<CHITIETKHUYENMAI> _CHITIETKHUYENMAIs;
		
		private EntitySet<CHITIETTHUCPHAM> _CHITIETTHUCPHAMs;
		
		private EntityRef<LOAITHUCPHAM> _LOAITHUCPHAM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaThucPhamChanging(int value);
    partial void OnMaThucPhamChanged();
    partial void OnTenThucPhamChanging(string value);
    partial void OnTenThucPhamChanged();
    partial void OnMaLoaiThucPhamChanging(System.Nullable<int> value);
    partial void OnMaLoaiThucPhamChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnNgayDangChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDangChanged();
    partial void OnDuyetChanging(System.Nullable<int> value);
    partial void OnDuyetChanged();
    partial void OnCheckSaleChanging(System.Nullable<int> value);
    partial void OnCheckSaleChanged();
    partial void OnTrungBinhDanhGiaChanging(System.Nullable<double> value);
    partial void OnTrungBinhDanhGiaChanged();
    partial void OnGiamGiaChanging(System.Nullable<int> value);
    partial void OnGiamGiaChanged();
    #endregion
		
		public THUCPHAM()
		{
			this._BINHLUANs = new EntitySet<BINHLUAN>(new Action<BINHLUAN>(this.attach_BINHLUANs), new Action<BINHLUAN>(this.detach_BINHLUANs));
			this._CHITIETDONHANGs = new EntitySet<CHITIETDONHANG>(new Action<CHITIETDONHANG>(this.attach_CHITIETDONHANGs), new Action<CHITIETDONHANG>(this.detach_CHITIETDONHANGs));
			this._CHITIETKHUYENMAIs = new EntitySet<CHITIETKHUYENMAI>(new Action<CHITIETKHUYENMAI>(this.attach_CHITIETKHUYENMAIs), new Action<CHITIETKHUYENMAI>(this.detach_CHITIETKHUYENMAIs));
			this._CHITIETTHUCPHAMs = new EntitySet<CHITIETTHUCPHAM>(new Action<CHITIETTHUCPHAM>(this.attach_CHITIETTHUCPHAMs), new Action<CHITIETTHUCPHAM>(this.detach_CHITIETTHUCPHAMs));
			this._LOAITHUCPHAM = default(EntityRef<LOAITHUCPHAM>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaThucPham", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaThucPham
		{
			get
			{
				return this._MaThucPham;
			}
			set
			{
				if ((this._MaThucPham != value))
				{
					this.OnMaThucPhamChanging(value);
					this.SendPropertyChanging();
					this._MaThucPham = value;
					this.SendPropertyChanged("MaThucPham");
					this.OnMaThucPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenThucPham", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string TenThucPham
		{
			get
			{
				return this._TenThucPham;
			}
			set
			{
				if ((this._TenThucPham != value))
				{
					this.OnTenThucPhamChanging(value);
					this.SendPropertyChanging();
					this._TenThucPham = value;
					this.SendPropertyChanged("TenThucPham");
					this.OnTenThucPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiThucPham", DbType="Int")]
		public System.Nullable<int> MaLoaiThucPham
		{
			get
			{
				return this._MaLoaiThucPham;
			}
			set
			{
				if ((this._MaLoaiThucPham != value))
				{
					if (this._LOAITHUCPHAM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiThucPhamChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiThucPham = value;
					this.SendPropertyChanged("MaLoaiThucPham");
					this.OnMaLoaiThucPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDang", DbType="Date")]
		public System.Nullable<System.DateTime> NgayDang
		{
			get
			{
				return this._NgayDang;
			}
			set
			{
				if ((this._NgayDang != value))
				{
					this.OnNgayDangChanging(value);
					this.SendPropertyChanging();
					this._NgayDang = value;
					this.SendPropertyChanged("NgayDang");
					this.OnNgayDangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Duyet", DbType="Int")]
		public System.Nullable<int> Duyet
		{
			get
			{
				return this._Duyet;
			}
			set
			{
				if ((this._Duyet != value))
				{
					this.OnDuyetChanging(value);
					this.SendPropertyChanging();
					this._Duyet = value;
					this.SendPropertyChanged("Duyet");
					this.OnDuyetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckSale", DbType="Int")]
		public System.Nullable<int> CheckSale
		{
			get
			{
				return this._CheckSale;
			}
			set
			{
				if ((this._CheckSale != value))
				{
					this.OnCheckSaleChanging(value);
					this.SendPropertyChanging();
					this._CheckSale = value;
					this.SendPropertyChanged("CheckSale");
					this.OnCheckSaleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrungBinhDanhGia", DbType="Float")]
		public System.Nullable<double> TrungBinhDanhGia
		{
			get
			{
				return this._TrungBinhDanhGia;
			}
			set
			{
				if ((this._TrungBinhDanhGia != value))
				{
					this.OnTrungBinhDanhGiaChanging(value);
					this.SendPropertyChanging();
					this._TrungBinhDanhGia = value;
					this.SendPropertyChanged("TrungBinhDanhGia");
					this.OnTrungBinhDanhGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiamGia", DbType="Int")]
		public System.Nullable<int> GiamGia
		{
			get
			{
				return this._GiamGia;
			}
			set
			{
				if ((this._GiamGia != value))
				{
					this.OnGiamGiaChanging(value);
					this.SendPropertyChanging();
					this._GiamGia = value;
					this.SendPropertyChanged("GiamGia");
					this.OnGiamGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THUCPHAM_BINHLUAN", Storage="_BINHLUANs", ThisKey="MaThucPham", OtherKey="MaThucPham")]
		public EntitySet<BINHLUAN> BINHLUANs
		{
			get
			{
				return this._BINHLUANs;
			}
			set
			{
				this._BINHLUANs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THUCPHAM_CHITIETDONHANG", Storage="_CHITIETDONHANGs", ThisKey="MaThucPham", OtherKey="MaThucPham")]
		public EntitySet<CHITIETDONHANG> CHITIETDONHANGs
		{
			get
			{
				return this._CHITIETDONHANGs;
			}
			set
			{
				this._CHITIETDONHANGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THUCPHAM_CHITIETKHUYENMAI", Storage="_CHITIETKHUYENMAIs", ThisKey="MaThucPham", OtherKey="MaThucPham")]
		public EntitySet<CHITIETKHUYENMAI> CHITIETKHUYENMAIs
		{
			get
			{
				return this._CHITIETKHUYENMAIs;
			}
			set
			{
				this._CHITIETKHUYENMAIs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THUCPHAM_CHITIETTHUCPHAM", Storage="_CHITIETTHUCPHAMs", ThisKey="MaThucPham", OtherKey="MaThucPham")]
		public EntitySet<CHITIETTHUCPHAM> CHITIETTHUCPHAMs
		{
			get
			{
				return this._CHITIETTHUCPHAMs;
			}
			set
			{
				this._CHITIETTHUCPHAMs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAITHUCPHAM_THUCPHAM", Storage="_LOAITHUCPHAM", ThisKey="MaLoaiThucPham", OtherKey="MaLoaiThucPham", IsForeignKey=true)]
		public LOAITHUCPHAM LOAITHUCPHAM
		{
			get
			{
				return this._LOAITHUCPHAM.Entity;
			}
			set
			{
				LOAITHUCPHAM previousValue = this._LOAITHUCPHAM.Entity;
				if (((previousValue != value) 
							|| (this._LOAITHUCPHAM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAITHUCPHAM.Entity = null;
						previousValue.THUCPHAMs.Remove(this);
					}
					this._LOAITHUCPHAM.Entity = value;
					if ((value != null))
					{
						value.THUCPHAMs.Add(this);
						this._MaLoaiThucPham = value.MaLoaiThucPham;
					}
					else
					{
						this._MaLoaiThucPham = default(Nullable<int>);
					}
					this.SendPropertyChanged("LOAITHUCPHAM");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BINHLUANs(BINHLUAN entity)
		{
			this.SendPropertyChanging();
			entity.THUCPHAM = this;
		}
		
		private void detach_BINHLUANs(BINHLUAN entity)
		{
			this.SendPropertyChanging();
			entity.THUCPHAM = null;
		}
		
		private void attach_CHITIETDONHANGs(CHITIETDONHANG entity)
		{
			this.SendPropertyChanging();
			entity.THUCPHAM = this;
		}
		
		private void detach_CHITIETDONHANGs(CHITIETDONHANG entity)
		{
			this.SendPropertyChanging();
			entity.THUCPHAM = null;
		}
		
		private void attach_CHITIETKHUYENMAIs(CHITIETKHUYENMAI entity)
		{
			this.SendPropertyChanging();
			entity.THUCPHAM = this;
		}
		
		private void detach_CHITIETKHUYENMAIs(CHITIETKHUYENMAI entity)
		{
			this.SendPropertyChanging();
			entity.THUCPHAM = null;
		}
		
		private void attach_CHITIETTHUCPHAMs(CHITIETTHUCPHAM entity)
		{
			this.SendPropertyChanging();
			entity.THUCPHAM = this;
		}
		
		private void detach_CHITIETTHUCPHAMs(CHITIETTHUCPHAM entity)
		{
			this.SendPropertyChanging();
			entity.THUCPHAM = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TINNHANLIENHE")]
	public partial class TINNHANLIENHE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaTinNhan;
		
		private string _TenKH;
		
		private string _Email;
		
		private string _TieuDe;
		
		private string _NoiDungTuKH;
		
		private System.Nullable<int> _MaNhanVien;
		
		private string _TraLoi;
		
		private System.Nullable<System.DateTime> _NgayNhan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTinNhanChanging(int value);
    partial void OnMaTinNhanChanged();
    partial void OnTenKHChanging(string value);
    partial void OnTenKHChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnTieuDeChanging(string value);
    partial void OnTieuDeChanged();
    partial void OnNoiDungTuKHChanging(string value);
    partial void OnNoiDungTuKHChanged();
    partial void OnMaNhanVienChanging(System.Nullable<int> value);
    partial void OnMaNhanVienChanged();
    partial void OnTraLoiChanging(string value);
    partial void OnTraLoiChanged();
    partial void OnNgayNhanChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayNhanChanged();
    #endregion
		
		public TINNHANLIENHE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTinNhan", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaTinNhan
		{
			get
			{
				return this._MaTinNhan;
			}
			set
			{
				if ((this._MaTinNhan != value))
				{
					this.OnMaTinNhanChanging(value);
					this.SendPropertyChanging();
					this._MaTinNhan = value;
					this.SendPropertyChanged("MaTinNhan");
					this.OnMaTinNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKH", DbType="NVarChar(30)")]
		public string TenKH
		{
			get
			{
				return this._TenKH;
			}
			set
			{
				if ((this._TenKH != value))
				{
					this.OnTenKHChanging(value);
					this.SendPropertyChanging();
					this._TenKH = value;
					this.SendPropertyChanged("TenKH");
					this.OnTenKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieuDe", DbType="NVarChar(100)")]
		public string TieuDe
		{
			get
			{
				return this._TieuDe;
			}
			set
			{
				if ((this._TieuDe != value))
				{
					this.OnTieuDeChanging(value);
					this.SendPropertyChanging();
					this._TieuDe = value;
					this.SendPropertyChanged("TieuDe");
					this.OnTieuDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDungTuKH", DbType="NVarChar(1000)")]
		public string NoiDungTuKH
		{
			get
			{
				return this._NoiDungTuKH;
			}
			set
			{
				if ((this._NoiDungTuKH != value))
				{
					this.OnNoiDungTuKHChanging(value);
					this.SendPropertyChanging();
					this._NoiDungTuKH = value;
					this.SendPropertyChanged("NoiDungTuKH");
					this.OnNoiDungTuKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanVien", DbType="Int")]
		public System.Nullable<int> MaNhanVien
		{
			get
			{
				return this._MaNhanVien;
			}
			set
			{
				if ((this._MaNhanVien != value))
				{
					this.OnMaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._MaNhanVien = value;
					this.SendPropertyChanged("MaNhanVien");
					this.OnMaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TraLoi", DbType="NVarChar(1000)")]
		public string TraLoi
		{
			get
			{
				return this._TraLoi;
			}
			set
			{
				if ((this._TraLoi != value))
				{
					this.OnTraLoiChanging(value);
					this.SendPropertyChanging();
					this._TraLoi = value;
					this.SendPropertyChanged("TraLoi");
					this.OnTraLoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayNhan", DbType="Date")]
		public System.Nullable<System.DateTime> NgayNhan
		{
			get
			{
				return this._NgayNhan;
			}
			set
			{
				if ((this._NgayNhan != value))
				{
					this.OnNgayNhanChanging(value);
					this.SendPropertyChanging();
					this._NgayNhan = value;
					this.SendPropertyChanged("NgayNhan");
					this.OnNgayNhanChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
